import Header from "./components/Header";
import { GlobalProvider } from "./context/global";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        <GlobalProvider>
          <Header />
          {children}
          <Toaster />
        </GlobalProvider>
      </body>
    </html>
  );
}
